export const IMAGEKIT_URL_ENDPOINT = 'YOUR_IMAGEKIT_URL_ENDPOINT';
export const IMAGEKIT_PUBLIC_KEY = 'YOUR_IMAGEKIT_PUBLIC_KEY';
export const IMAGEKIT_AUTH_ENDPOINT = 'YOUR_IMAGEKIT_AUTH_ENDPOINT';
export const IMAGEKIT_ENDPOINT = 'YOUR_IMAGEKIT_ENDPOINT';
export const BASE_API_URL = 'YOUR_API_URLT';
